allow-licenses:
  - '0BSD'
  - 'Apache-2.0'
  - 'BSL-1.0'
  - 'BSD-1-Clause'
  - 'BSD-2-Clause-FreeBSD'
  - 'BSD-2-Clause'
  - 'BSD-3-Clause-Attribution'
  - 'BSD-3-Clause'
  - 'BSD-Source-Code'
  - 'bzip2-1.0.6'
  - 'CC-BY-3.0'
  - 'CC-BY-4.0'
  - 'CC0-1.0'
  - 'curl'
  - 'ISC'
  - 'JSON'
  - 'MIT'
  - 'MPL-2.0'
  - 'NTP'
  - 'OFL-1.0'
  - 'OLDAP-2.8'
  - 'OpenSSL'
  - 'PDDL-1.0'
  - 'PostgreSQL'
  - 'Python-2.0'
  - 'Spencer-94'
  - 'Unicode-DFS-2015'
  - 'Unicode-DFS-2016'
  - 'Unlicense'
  - 'WTFPL'
  - 'X11'
  - 'zlib-acknowledgement'
  - 'Zlib'
