allow-licenses:
  - '0BSD'
  - 'Apache-2.0'
  - 'Apache-2.0 AND MIT'
  - 'BlueOak-1.0.0'
  - 'BSD-1-Clause'
  - 'BSD-2-Clause-FreeBSD'
  - 'BSD-2-Clause'
  - 'BSD-3-Clause-Attribution'
  - 'BSD-3-Clause'
  - 'BSL-1.0'
  - 'CC-BY-3.0'
  - 'CC-BY-4.0'
  - 'CC0-1.0'
  - 'curl'
  - 'ISC'
  - 'ISC AND MIT'
  - 'JSON'
  - 'MIT'
  - 'OpenSSL'
  - 'PDDL-1.0'
  - 'PostgreSQL'
  - 'Python-2.0'
  - 'Unlicense'
  - 'WTFPL'
  - 'Zlib'
