# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: AWS Amplify Developer Documentation
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com 
github:
  repository_url: https://github.com/aws-amplify/amplify-js/edit/master/docs/

show_downloads: "true"
include: 
- api
- api/assets
- api/classes
- api/enums
- api/interfaces
- api/modules

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/


# Build settings
markdown: kramdown
kramdown:
  parse_block_html: true
plugins:
  - jekyll-feed
  - jekyll-sitemap
future: true  


# Amplify theme settings
amplify:
    baseurl: /amplify-js # Since the site is deployed under https://aws-amplify.github.io/amplify-js
    color_theme:  # Available themes: blue (default), green, purple, red and yellow
    header:
        logo:
            text: AWS Amplify
            image: true
            platform: for JavaScript
        nav:
            - item_name: Get Started
              item_url: '/media/get_started'
            - item_name: Guides
              item_url: '/media/developer_guide'
            - item_name: Tutorials
              item_url: '/media/tutorials'
            - item_name: Toolchain
              item_url: '/media/toolchain'
            - item_name: UI Components
              item_url: '/media/ui_library'
            - item_name: API
              item_url: '/api/'
            #- item_name: 
            #  item_icon: github
            #  item_external_url: 'https://github.com/aws-amplify/amplify-js'
    footer:
        content:
            logo:
                text: AWS Amplify is supported by Amazon Web Services
                image: true
            copyright: Â© 2017-2018 Amazon.com, Inc. or its affiliates. All Rights Reserved.
        social_list:
            - network_name: gitter
              profile_url: 'https://gitter.im/AWS-Amplify/Lobby/'
            - network_name: github
              profile_url: 'https://github.com/aws-amplify/amplify-js'
            - network_name: twitter
              profile_url: 'https://twitter.com/search?q=%23awsamplify&src=typd'
            - network_name: youtube
              profile_url: 'https://www.youtube.com/watch?v=vAjf3lyjf8c'
              
    google_analytics:
        tracking_code: # Add your Google Analytics tracking code to activate Google Analytics
    comments:
        disqus_forum_shortname: 'aws-amplify' # Add your disqus forum shortname to activate comments

# SASS settings
sass:
    sass_dir: ./amplify-theme/_sass
    style: :compressed

# Jekyll settings
layouts_dir: ./amplify-theme/_layouts
includes_dir: ./amplify-theme/_includes
exclude: [ 'README.md', 'CHANGELOG.md' ]
permalink: /:title

category_list:
    - category: SetupAndInstallation
      title: Setup & Installation
      excerpt: 
      base_url: 'get_started_docs'
      subs:
        - title: Get Started
          excerpt: get started excerpt
          url: '/media/get_started_docs'
          icon: '/images/icons/Misc/Present.svg'
        - title: Amplify CLI
          excerpt: CLI excerpt
          url: '/media/cli_guide'
          icon: '/images/icons/Misc/Present.svg'
    - category: CloudFeatures
      title: Cloud Features
      excerpt: Add cloud features to your app quickly using our toolchain and declarative APIs.
      base_url: '/media/analytics_guide'
      subs:
        - title: Analytics 
          excerpt: Drop-in analytics to track user sessions, custom user attributes, and in-app metrics.
          cta: Read more
          class: aws-icon-ps-60-pie-bar-charts 
          url: '/media/analytics_guide'
          icon: '/images/icons/Misc/Cloud.svg'
          services:
            - title: Amazon Pinpoint,
              url: https://aws.amazon.com/pinpoint/
            - title: Amazon Kinesis,
              url: https://aws.amazon.com/kinesis/
            - title: Custom Plugin
              url: https://aws-amplify.github.io/amplify-js/media/analytics_guide#using-a-custom-plugin
        - title: API 
          excerpt: A simple and secure solution for making HTTP requests using REST and GraphQL, with support for real-time data.
          cta: Read more
          class: aws-icon-ps-60-database-server
          url: '/media/api_guide' 
          icon: '/images/icons/Misc/Cloud.svg'   
          services: 
            - title: Amazon API Gateway,
              url: https://aws.amazon.com/api-gateway
            - title: AWS AppSync
              url: https://aws.amazon.com/appsync
        - title: Authentication
          excerpt:  Authentication APIs with pre-built UI components for your app.  
          cta: Read more
          class: aws-icon-ps-60-shield-circle
          url: '/media/authentication_guide'
          icon: '/images/icons/Misc/Cloud.svg'
          services:
            - title: Amazon Cognito,
              url: https://aws.amazon.com/cognito/
            - title: OAuth 2.0 ,
              url: https://aws.amazon.com/cognito/
            - title: Custom Plugin
              url:  
        - title: Interactions 
          excerpt: Create conversational bots powered by deep learning technologies.
          cta: Read more
          class: aws-icon-ps-60-bubble-gear
          url: '/media/interactions_guide'   
          icon: '/images/icons/Misc/Cloud.svg'
          services:
              - title: Amazon Lex
                url: https://aws.amazon.com/lex/
        - title: PubSub 
          excerpt: Connect your app to message-oriented middleware on the cloud.
          cta: Read more
          class: aws-icon-ps-60-circular-circuit
          url: '/media/pub_sub_guide'   
          icon: '/images/icons/Misc/Cloud.svg'
          services:
              - title: AWS IoT,
                url: https://aws.amazon.com/iot/
              - title: Generic MQTT,
                url: https://docs.aws.amazon.com/iot/latest/developerguide/protocols.html#mqtt
              - title: Custom Plugin
                url:  
        - title: Push Notifications 
          excerpt: Push notifications with campaign analytics and targeting.
          cta: Read more
          class: aws-icon-ps-60-device-message
          url: '/media/push_notifications_setup'   
          icon: '/images/icons/Misc/Cloud.svg'
          services:
              - title: Amazon Pinpoint
                url: https://aws.amazon.com/pinpoint/
        - title: Storage 
          excerpt: A simple mechanism for managing user content in public, protected or private storage.
          cta: Read more
          class: aws-icon-ps-60-file-box
          url: '/media/storage_guide'   
          icon: '/images/icons/Misc/Cloud.svg'
          services:
              - title: Amazon S3
                url: https://aws.amazon.com/s3/
    - category: UtilityModules
      title: Utility Modules
      excerpt: Common programming utilities that you can use with your app.
      base_url: '/media/cache_guide'
      subs:
        - title: Cache 
          excerpt: A generic LRU cache for storing data with priority and expiration settings. 
          cta: Read more
          url: '/media/cache_guide'  
          icon: '/images/icons/Misc/Gear-Icon.svg'
        - title: Hub  
          excerpt: A lightweight local event bus for your app.
          cta: Read more
          url: '/media/hub_guide' 
          icon: '/images/icons/Misc/Gear-Icon.svg'
        - title: I18n  
          excerpt: A lightweight internationalization solution.
          cta: Read more
          url: '/media/i18n_guide'  
          icon: '/images/icons/Misc/Gear-Icon.svg'
        - title: Logger  
          excerpt: Console logging utility.
          cta: Read more
          url: '/media/logger_guide'  
          icon: '/images/icons/Misc/Gear-Icon.svg'
        - title: Service Worker 
          excerpt: A utility class to work with PWA and Service Worker APIs. 
          cta: Read more
          url: '/media/service_workers_guide'   
          icon: '/images/icons/Misc/Gear-Icon.svg'   
          
    - category: Toolchain
      title: Toolchain
      excerpt: Better developer experience when building and deploying your apps.
      base_url: '/media/cache_guide'
      subs:
        - title: Amplify CLI 
          excerpt: Manage all of your services in one unified tool with Amplify Command Line Interface
          cta: Read more
          url: '/media/cli_guide'  
          icon: '/images/icons/Misc/Present.svg'
        - title: Hosting 
          excerpt: Deploy your Web app or static website for global CDN distribution with media streaming support.
          cta: Read more
          class: aws-icon-ps-60-network-nodes
          url: '/media/hosting_guide'   
          icon: '/images/icons/Misc/Present.svg'
          services:
              - title: Amazon CloudFront
                url: https://aws.amazon.com/cloudfront/
          
    - category: UserInterface
      title: User Interface
      excerpt: Bring your own front-end! We support the most popular front-end frameworks and libraries.
      base_url: '/media/angular_guide'
      subs:
        - title: Angular 
          excerpt: AWS Amplify provides Angular Components with aws-amplify-angular npm package.
          cta: Read more
          url: '/media/angular_guide' 
          icon: '/images/Logos/Angular-Color@1x.png'
          id: angular
        - title: React 
          excerpt: AWS Amplify provides React Components with aws-amplify-react npm package and a starter App.
          cta: Read more
          url: '/media/react_guide' 
          icon: '/images/Logos/React-Color@1x.png'
          id: react
        - title: React Native
          excerpt: AWS Amplify provides React Native Components with aws-amplify-react npm package and a starter App.
          cta: Read more
          url: '/media/react_native_guide' 
          icon: '/images/Logos/React-Color@1x.png'
          id: react-native
        - title: Vue.js
          excerpt: To help you start working with AWS Amplify, we provide a Starter App.
          cta: Read more
          url: '/media/vuejs_guide' 
          icon: '/images/Logos/Vue-Color@1x.png'
          id: vuejs
        - title: Ionic
          excerpt: AWS Amplify provides Angular Components that you can use with Ionic in aws-amplify-angular npm package.
          cta: Read more
          url: '/media/ionic_guide' 
          icon: '/images/Logos/Ionic-Color@1x.png'
          id: ionic

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"


examples:
  - title: Web apps
    url: 'web-apps' 
  - title: React Native apps
    url: 'react-native-apps'
  - title: Hybrid Mobile
    url: 'hybrid-mobile-apps'
  - title: Static Websites
    url: 'static-web-sites'
  - title: Code Examples
    url: 'examples'

styleguide:
  - title: Colors
    url: '#colors'
  - title: 'Typography'
    url: '#typography'
  - title: 'Controls'
    url: '#controls--inputs'
  - title: 'Widgets'
    url: '#widgets'
  - title: Components
    url: '#aws-components'

js_libraries:
  - title: React
    url: '?platform=react'
  - title: React Native
    url: '?platform=react-native'
  - title: Angular
    url: '?platform=angular'
  - title: JavaScript (no library)
    url: '?platform=purejs'