name: 'Canary E2E Tests'

on:
  workflow_call:
    inputs:
      test_name:
        required: true
        type: string
      framework:
        required: true
        type: string
      category:
        required: true
        type: string
      sample_name:
        required: true
        type: string
      spec:
        required: false
        type: string
        default: ''
      browser:
        required: false
        type: string
        default: ''
      amplifyjs_dir:
        required: false
        type: boolean
        default: false
      timeout_minutes:
        required: true
        type: number
      retry_count:
        required: true
        type: number

env:
  NPM_REGISTRY: http://localhost:4873/
  NPM_USER: circleci
  NPM_PASS: circleci
  NPM_EMAIL: circleci@amplify.js
  AMPLIFY_DIR: /home/runner/work/amplify-js/amplify-js/amplify-js
  CYPRESS_GOOGLE_CLIENTID: ${{ secrets.CYPRESS_GOOGLE_CLIENTID }}
  CYPRESS_GOOGLE_CLIENT_SECRET: ${{ secrets.CYPRESS_GOOGLE_CLIENT_SECRET }}
  CYPRESS_GOOGLE_REFRESH_TOKEN: ${{ secrets.CYPRESS_GOOGLE_REFRESH_TOKEN }}

jobs:
  canary-e2e-test:
    name: 'E2E: ${{ inputs.test_name }}'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser:
          - ${{ fromJson(inputs.browser) }}
        sample_name:
          - ${{ fromJson(inputs.sample_name) }}
      fail-fast: false
    timeout-minutes: ${{ inputs.timeout_minutes }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3.4.0 https://github.com/actions/checkout/commit/24cb9080177205b6e8c946b17badbe402adc938f
        with:
          # Minimal depth 2 so we can checkout the commit before possible merge commit.
          fetch-depth: 2
          path: amplify-js          
      - name: Setup Node.js 16
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0 https://github.com/actions/setup-node/commit/64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c
        with:
          node-version: 16
        env:
          SEGMENT_DOWNLOAD_TIMEOUT_MINS: 2

      - name: Install
        run: yarn
        shell: bash
        working-directory: ./amplify-js
      - name: Bootstrap
        run: yarn bootstrap
        shell: bash
        working-directory: ./amplify-js
      - name: Build packages
        run: yarn build
        shell: bash
        working-directory: ./amplify-js
        
      - name: Setup samples staging repository
        uses: ./amplify-js/.github/actions/setup-samples-staging
        with:
          GH_TOKEN_STAGING_READ: ${{ secrets.GH_TOKEN_STAGING_READ }}

      - name: Modify package.json to run against aws-amplify latest 
        run: |
          tmpfile=$(mktemp)
          cp samples/${{ inputs.framework }}/${{ inputs.category }}/${{ matrix.sample_name }}/package.json "$tmpfile" &&
          jq 'select(.dependencies) |= with_entries(select(.key | startswith("aws-amplify")).value = "latest")' samples/${{ inputs.framework }}/${{ inputs.category }}/${{ matrix.sample_name }}/package.json "$tmpfile" > samples/${{ inputs.framework }}/${{ inputs.category }}/${{ matrix.sample_name }}/package.json && rm -f -- "$tmpfile"
        working-directory: amplify-js-samples-staging
        
      - name: Run cypress tests for ${{ inputs.test_name }} dev
        run: |
          ../amplify-js/.circleci/retry-yarn-script.sh -s \
          "ci:test \
          ${{ inputs.framework }} \
          ${{ inputs.category }} \
          ${{ matrix.sample_name }} \
          ${{ inputs.spec }} \
          ${{ matrix.browser }} \
          dev \
          ${{ inputs.amplifyjs_dir == true && env.AMPLIFY_DIR || ''}}" \
          -n ${{ inputs.retry_count }}
        working-directory: amplify-js-samples-staging
        shell: bash
      - name: Run cypress tests for ${{ inputs.test_name }} prod
        run: |
          ../amplify-js/.circleci/retry-yarn-script.sh -s \
          "ci:test \
          ${{ inputs.framework }} \
          ${{ inputs.category }} \
          ${{ matrix.sample_name }} \
          ${{ inputs.spec }} \
          ${{ matrix.browser }} \
          prod \
          ${{ inputs.amplifyjs_dir == true && env.AMPLIFY_DIR || ''}}" \
          -n ${{ inputs.retry_count }}
        working-directory: amplify-js-samples-staging
        shell: bash
      - name: Upload artifact
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2 https://github.com/actions/upload-artifact/commit/0b7f8abb1508181956e8e162db84b466c27e18ce
        if: always()
        with:
          name: canary-e2e-test-artifacts
          if-no-files-found: ignore
          path: |
            amplify-js-samples-staging/cypress/videos
            amplify-js-samples-staging/cypress/screenshots
