name: Release Verification Tests

on: workflow_call

env:
  CYPRESS_GOOGLE_CLIENTID: ${{ secrets.CYPRESS_GOOGLE_CLIENTID }}
  CYPRESS_GOOGLE_CLIENT_SECRET: ${{ secrets.CYPRESS_GOOGLE_CLIENT_SECRET }}
  CYPRESS_GOOGLE_REFRESH_TOKEN: ${{ secrets.CYPRESS_GOOGLE_REFRESH_TOKEN }}

jobs:
  prebuild-ubuntu:
    uses: ./.github/workflows/callable-prebuild-amplify-js.yml
    with:
      runs_on: ubuntu-latest
  prebuild-macos:
    uses: ./.github/workflows/callable-prebuild-amplify-js.yml
    with:
      runs_on: macos-latest
  prebuild-samples-staging:
    secrets: inherit
    uses: ./.github/workflows/callable-prebuild-samples-staging.yml
  e2e:
    needs:
      - prebuild-macos
      - prebuild-ubuntu
      - prebuild-samples-staging
    secrets: inherit
    uses: ./.github/workflows/callable-e2e-tests.yml
  unit-tests:
    needs:
      - prebuild-ubuntu
    uses: ./.github/workflows/callable-unit-tests.yml
  bundle-size-tests:
    needs: prebuild-ubuntu
    uses: ./.github/workflows/callable-bundle-size-tests.yml
