on:
  workflow_call:
    secrets:
      GH_PAT:
        required: true

env:
  NPM_REGISTRY: http://localhost:4873/
  NPM_USER: circleci
  NPM_PASS: circleci
  NPM_EMAIL: circleci@amplify.js

jobs:
  e2e-tests:
    name: Runs E2E tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        BROWSER: [chrome, firefox]
    steps:
      - name: Checkout repository
        uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3.4.0 https://github.com/actions/checkout/commit/24cb9080177205b6e8c946b17badbe402adc938f
        with:
          # Minimal depth 2 so we can checkout the commit before possible merge commit.
          fetch-depth: 2
          path: aws-amplify
      - name: Setup node and build the repository
        uses: ./aws-amplify/.github/actions/node-and-build
      - name: Setup samples staging repository
        uses: ./aws-amplify/.github/actions/setup-samples-staging
        with:
          GH_PAT: ${{ secrets.GH_PAT }}
      - name: Load Verdaccio with AmplifyJs
        uses: ./aws-amplify/.github/actions/load-verdaccio-with-amplify-js
      - name: Run E2E test
        run: |
          ../aws-amplify/.circleci/retry-yarn-script.sh -s 'ci:test react storage storageApp storage ${{ matrix.BROWSER }}'
        working-directory: amplify-js-samples-staging
        shell: bash
