name: Unit Tests

on: workflow_call

jobs:
  get-package-list:
    uses: ./.github/workflows/callable-get-package-list.yml
  unit_test:
    name: Unit Test - ${{ matrix.package }}
    runs-on: ubuntu-latest
    needs: get-package-list
    strategy:
      matrix:
        package: ${{ fromJSON(needs.get-package-list.outputs.packages) }}
      fail-fast: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3.4.0 https://github.com/actions/checkout/commit/24cb9080177205b6e8c946b17badbe402adc938f
        with:
          path: amplify-js
      - name: Setup node and build the repository
        uses: ./amplify-js/.github/actions/node-and-build
      - name: Run tests
        working-directory: ./amplify-js
        env:
          TEST_PACKAGE: ${{ matrix.package.name }}
        run: npx lerna exec --scope $TEST_PACKAGE yarn test
      - name: Upload coverage report
        uses: codecov/codecov-action@eaaf4bedf32dbdc6b720b63067d99c4d77d6047d
        env:
          PACKAGE_DIRECTORY: ${{ matrix.package.path }}
        with:
          files: ./amplify-js/packages/${{ env.PACKAGE_DIRECTORY }}/coverage/coverage-final.json
          flags: ${{ env.PACKAGE_DIRECTORY }}
          fail_ci_if_error: true
