name: Capture Package Names List to Outputs

on:
  workflow_call:
    outputs:
      packages:
        description: The json encoded package list
        value: ${{ jobs.get-package-list.outputs.packages }}
jobs:
  get-package-list:
    name: Get packages list
    runs-on: ubuntu-latest
    steps:
      - name: Checkout AmplifyJs
        uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3.4.0 https://github.com/actions/checkout/commit/24cb9080177205b6e8c946b17badbe402adc938f
      - uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3.3.1
        id: cache-package-list
        with:
          path: |
            **/package-list.json
          key: ${{ runner.os }}-package-list-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-package-list-
        env:
          SEGMENT_DOWNLOAD_TIMEOUT_MINS: 2
      - name: Install
        if: steps.cache-package-list.outputs.cache-hit != 'true'
        run: yarn
        shell: bash
      # Need the repo checked out in order to read the file
      - name: Dump Package List
        if: steps.cache-package-list.outputs.cache-hit != 'true'
        run: |
          echo "packages=$(yarn lerna ll | egrep -v "lerna|Done|yarn" | jq -R -s -c 'split("\n")[:-1] | map({ name: split(" ")[0], path: split(" ")[-1]})')" > package-list.txt
      - name: Get Package List
        id: get_package_list
        run: |
          cat package-list.txt >> $GITHUB_OUTPUT
          cat package-list.txt
    outputs:
      packages: ${{ steps.get_package_list.outputs.packages }}
