name: Git Secrets Check
on: workflow_call

jobs:
  git_secrets_check:
    name: Scan for secrets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          path: amplify-js

      - name: Install git-secrets
        run: |
          git clone https://github.com/awslabs/git-secrets.git
          cd git-secrets
          sudo make install

      - name: Register AWS patterns and scan
        working-directory: ./amplify-js
        run: |
          git secrets --register-aws
          # Scan only the files in the current checkout (PR merge commit)
          git secrets --scan
