name: Push - release for feature preid

on:
  push:
    branches:
      # Change this to your branch name where "example-preid" corresponds to the preid you want your changes released on
      - feat/example-preid/main

jobs:
  e2e:
    secrets: inherit
    uses: ./.github/workflows/callable-e2e.yml
  parse-preid:
    name: Parse preid from branch
    runs-on: ubuntu-latest
    env:
      BRANCH: ${{ github.ref_name }}
    steps:
      - id: output_preid
        run: echo "preid=$(echo $BRANCH | cut -d \/ -f 2)" >> $GITHUB_OUTPUT
    outputs:
      preid: ${{ steps.output_preid.outputs.preid }}

  preid-release:
    needs:
      - e2e
      - parse-preid
    secrets: inherit
    uses: ./.github/workflows/callable-npm-publish-preid.yml
    # The preid should be detected from the branch name recommending feat/PREID/whatvever as branch naming pattern
    with:
      preid: ${{ needs.parse-preid.outputs.preid }}
